"""
Akira Forge Version Information
Auto-generated by create_version_branch.py
"""

__version__ = "1.1(stable)"
__version_number__ = "1.1"
__stability__ = "stable"
__version_info__ = tuple(map(int, __version_number__.split(".")))
